// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4HFuKrIGBulMiQzHzf7ikOSeFxPg1_JY',
    appId: '1:349395762696:web:07b6b49b34a3a59cf51bbd',
    messagingSenderId: '349395762696',
    projectId: 'chillparents',
    authDomain: 'chillparents.firebaseapp.com',
    storageBucket: 'chillparents.firebasestorage.app',
    measurementId: 'G-YWSX9F26T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRoSl4ODi7LS050GPf-X3IqcD5ykzo7aY',
    appId: '1:349395762696:android:8bfc4352c474677ef51bbd',
    messagingSenderId: '349395762696',
    projectId: 'chillparents',
    storageBucket: 'chillparents.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrXUJulAXOJG727qGxcsyIx1veg_AsPg',
    appId: '1:349395762696:ios:f9af33f133f071d6f51bbd',
    messagingSenderId: '349395762696',
    projectId: 'chillparents',
    storageBucket: 'chillparents.firebasestorage.app',
    iosBundleId: 'com.example.chillParents',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrXUJulAXOJG727qGxcsyIx1veg_AsPg',
    appId: '1:349395762696:ios:f9af33f133f071d6f51bbd',
    messagingSenderId: '349395762696',
    projectId: 'chillparents',
    storageBucket: 'chillparents.firebasestorage.app',
    iosBundleId: 'com.example.chillParents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4HFuKrIGBulMiQzHzf7ikOSeFxPg1_JY',
    appId: '1:349395762696:web:ff09ace065dc1124f51bbd',
    messagingSenderId: '349395762696',
    projectId: 'chillparents',
    authDomain: 'chillparents.firebaseapp.com',
    storageBucket: 'chillparents.firebasestorage.app',
    measurementId: 'G-0VXZV5E0JW',
  );
}
